name: maven-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4    
    - name: set up jdk 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - name: cache maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: build and test with maven
      run: mvn -B clean install -P pre-release -Djavacpp.platform=linux-x86_64
    - name: upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: target/karate-reports/
        retention-days: 5        